# -*- coding: utf-8 -*-

from . import res_partner
from . import hr_employee
from . import res_config_settings
from . import clublog
from . import clubcustomfield
from . import clubcustomfieldvalue
from . import clubcustomfield_mixin
from . import club_security_mixin
from . import club
from . import clubsubclub
from . import clubboard
from . import clubdepartment
from . import clubpool
from . import clubteam
from . import clubmember
from . import clubmember_membership_additionalproduct
from . import clubmember_membership
from . import clubmember_membership_history
from . import clubmember_billing_run
from . import clubmember_state
from . import clubmember_state_history
from . import clubmember_state_rule
from . import club_member_state_rule_dry_run_wizard
from . import clubmember_guardian
from . import club_member_mail_wizard
from . import club_member_single_billing_wizard
from . import club_member_transfer_wizard
from . import clubrole
from . import clubfield_mixin
from . import clubapiconfig